
import { createContext, useState, useContext, ReactNode, FC } from 'react';

type Language = 'id' | 'en';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const translations = {
  id: {
    // Global & Common
    'app.name': 'SPM~ITSB',
    'status.pending': 'Menunggu Konfirmasi',
    'status.planned': 'Terjadwal',
    'status.progress': 'Sedang Berjalan',
    'status.submitted': 'Menunggu Verifikasi',
    'status.review': 'Tinjauan Ka. Unit',
    'status.completed': 'Selesai',
    'status.user_active': 'Aktif',
    'status.user_inactive': 'Tidak Aktif',
    'status.user_role': 'Peran Pengguna',
    
    'role.superadmin': 'Super Admin',
    'role.admin': 'Administrator',
    'role.lead': 'Lead Auditor',
    'role.auditor': 'Auditor',
    'role.depthead': 'Kepala Unit',
    'role.auditee': 'Auditee (Unit)',

    // Alerts & Errors
    'alert.file_too_big': 'Ukuran file terlalu besar (Maks 5MB).',
    'alert.no_evidence': 'Tidak ada bukti/tautan untuk dibuka.',
    'alert.file_error': 'Gagal membuka file. Format data mungkin rusak.',
    'alert.file_invalid': 'Data file tidak valid.',

    // Confirmations
    'confirm.general': 'Konfirmasi Tindakan',
    'confirm.save': 'Apakah Anda yakin ingin MENYIMPAN data ini?',
    'confirm.delete': 'Apakah Anda yakin ingin MENGHAPUS data ini? Tindakan ini tidak dapat dibatalkan.',
    'confirm.update': 'Apakah Anda yakin ingin MEMPERBARUI data ini?',
    'confirm.add': 'Apakah Anda yakin ingin MENAMBAH data baru?',
    'confirm.action': 'Apakah Anda yakin ingin melanjutkan tindakan ini?',
    'confirm.cancel': 'Apakah Anda yakin ingin membatalkan?',
    'confirm.yes': 'Ya, Lanjutkan',
    'confirm.no': 'Batal',

    // Sidebar
    'nav.dashboard': 'Dashboard',
    'nav.schedule': 'Jadwal Audit',
    'nav.userMgmt': 'Manajemen Pengguna',
    'nav.template': 'Instrumen Audit',
    'nav.master': 'Data Unit Kerja',
    'nav.newAudit': 'Buat Penugasan',
    'nav.execution': 'Pelaksanaan Audit',
    'nav.report': 'Laporan & AI',
    'nav.settings': 'Pengaturan Sistem',
    'nav.logout': 'Keluar',
    'nav.my_assign': 'Penugasan Saya',
    'nav.my_audits': 'Audit Unit Saya',
    'nav.my_reports': 'Riwayat Laporan',
    'nav.dept_reports': 'Laporan Unit',
    'nav.all_exec': 'Monitoring Pelaksanaan',
    'nav.all_active': 'Audit Aktif',

    // Dashboard
    'dash.title': 'Dashboard Audit Mutu',
    'dash.subtitle': 'Ringkasan aktivitas dan status penjaminan mutu internal.',
    'dash.btnNew': '+ Buat Penugasan',
    'dash.total': 'Total Audit',
    'dash.inProgress': 'Sedang Berjalan',
    'dash.completed': 'Selesai',
    'dash.findings': 'Temuan Mayor',
    'dash.submitted': 'Verifikasi Auditor',
    'dash.review': 'Validasi Ka. Unit',
    'dash.recentHistory': 'Aktivitas Audit Terbaru',
    'dash.th.dept': 'Unit / Prodi',
    'dash.th.std': 'Standar',
    'dash.th.status': 'Status',
    'dash.th.date': 'Tanggal',
    'dash.th.auditor': 'Auditor',
    'dash.empty': 'Belum ada data audit. Silakan buat penugasan baru.',
    'dash.welcome.auditee': 'Area Unit Kerja: ',
    'dash.welcome.auditee.msg': 'Halaman ini khusus menampilkan data audit untuk unit kerja Anda. Mohon lengkapi bukti (evidence) dan rencana tindak lanjut pada audit yang berstatus "Sedang Berjalan".',
    'dash.welcome.auditor': 'Area Kerja Auditor',
    'dash.welcome.auditor.msg': 'Menampilkan daftar penugasan audit Anda. Silakan lakukan penilaian kepatuhan, verifikasi bukti, dan berikan catatan temuan.',

    // Audit Schedule (Jadwal)
    'sched.title': 'Jadwal Audit Mutu',
    'sched.subtitle': 'Perencanaan, penjadwalan, dan visualisasi lini masa audit.',
    'sched.view.list': 'Daftar',
    'sched.view.calendar': 'Kalender',
    'sched.btn.new': '+ Jadwal Baru',
    'sched.upcoming': 'Jadwal Mendatang / Menunggu Konfirmasi',
    'sched.history': 'Riwayat Pelaksanaan (Aktif & Selesai)',
    'sched.btn.start_all': 'Mulai Semua (Terjadwal)',
    'sched.empty_upcoming': 'Tidak ada jadwal audit mendatang.',
    'sched.empty_history': 'Belum ada riwayat pelaksanaan audit.',
    'sched.modal.new_title': 'Buat Jadwal Audit Baru',
    'sched.modal.reschedule_title': 'Jadwal Ulang Audit',
    'sched.label.date': 'Tanggal Pelaksanaan',
    'sched.label.auditor': 'Auditor Bertugas',
    'sched.label.unit': 'Unit / Auditee',
    'sched.label.std': 'Standar Acuan',
    'sched.label.name': 'Nama Kegiatan',
    'sched.confirm.title': 'Konfirmasi Jadwal',
    'sched.confirm.msg': 'Jadwal ini akan dikirim ke Kepala Unit untuk persetujuan.',
    'sched.action.start': 'Mulai',
    'sched.action.reschedule': 'Ubah Jadwal',
    'sched.action.delete': 'Hapus',
    'sched.alert.overdue': 'Terlewat',

    // New Audit Form
    'new.title': 'Konfigurasi Penugasan',
    'new.step1': 'Data Penugasan',
    'new.step2': 'Review Instrumen',
    'new.editor.title': 'Review Instrumen Audit',
    'new.editor.subtitle': 'Tinjau, sunting, atau tambahkan pertanyaan audit secara manual sebelum dikirim.',
    'new.label.std': '1. Pilih Standar Instrumen (Wajib)',
    'new.label.unit': '2. Pilih Auditee (Unit Kerja/Prodi)',
    'new.label.auditor': '3. Pilih Auditor (Semua User Aktif)',
    'new.label.name': '4. Nama Penugasan Audit',
    'new.label.desc': '5. Deskripsi / Catatan Tambahan',
    'new.placeholder.unit': '-- Pilih Unit / Program Studi --',
    'new.placeholder.auditor': '-- Pilih Auditor --',
    'new.warn.conflict': 'Info: Auditor dari unit yang sama disembunyikan untuk menghindari Konflik Kepentingan.',
    'new.btn.cancel': 'Batal',
    'new.btn.next': 'Lanjut',
    'new.btn.back': 'Kembali',
    'new.btn.finalize': 'Kirim Penugasan',
    'new.btn.generate': 'Memproses Data...',
    'new.btn.addManual': '+ Tambah Pertanyaan',
    'new.error': 'Gagal menghubungkan ke layanan AI. Pastikan koneksi internet stabil.',
    'new.access_denied': 'Akses Ditolak',
    'new.access_msg': 'Anda tidak memiliki wewenang untuk membuat Penugasan Audit baru.',
    'new.confirm.title': 'Kirim Penugasan?',
    'new.confirm.msg': 'Penugasan ini akan dikirim ke Kepala Unit terkait untuk konfirmasi jadwal.',
    'new.confirm.wait': 'Status: Menunggu Konfirmasi',
    'new.confirm.wait_msg': 'Audit tidak dapat dimulai (Sedang Berjalan) sampai Kepala Unit menyetujui jadwal yang diajukan.',
    'new.del.title': 'Hapus Pertanyaan?',
    'new.del.msg': 'Pertanyaan ini akan dihapus dari daftar instrumen audit saat ini.',
    'new.del.confirm': 'Ya, Hapus',

    // Execution
    'exec.list.title': 'Pelaksanaan Audit',
    'exec.list.subtitle': 'Pilih audit untuk mulai mengisi kertas kerja (KK) atau melakukan verifikasi.',
    'exec.search': 'Cari Unit / Nama Audit...',
    'exec.no_active': 'Tidak ada audit aktif',
    'exec.no_active_msg': 'Semua tugas audit telah selesai atau belum memasuki masa pelaksanaan.',
    'exec.progress': 'Progres Pengisian',
    'exec.filter.all': 'Semua',
    'exec.filter.unfilled': 'Belum Diisi',
    'exec.search_placeholder': 'Cari pertanyaan/indikator...',
    'exec.no_match': 'Tidak ada pertanyaan yang sesuai dengan filter.',
    'exec.btn.save': 'Simpan Draft',
    'exec.btn.complete': 'Selesai / Submit',
    'exec.btn.submit_assess': 'Kirim Penilaian',
    'exec.btn.verify_send': 'Verifikasi & Kirim',
    'exec.btn.approve': 'Setujui (Approve)',
    'exec.btn.back': 'Kembali',
    'exec.btn.open_file': 'Buka Bukti',
    'exec.label.evidence': 'Bukti (Evidence)',
    'exec.label.notes': 'Catatan Auditor',
    'exec.label.action_plan': 'Rencana Tindak Lanjut (RTL)',
    'exec.label.verification': 'Verifikasi Auditor',
    'exec.label.verdict': 'Keputusan Auditor',
    'exec.label.self_eval': 'Penilaian Mandiri (Auditee)',
    'exec.label.claim': 'Klaim Penilaian',
    'exec.help.upload': '*Anda dapat menempelkan URL eksternal ATAU mengunggah file (Maks 5MB).',
    'exec.placeholder.evidence': 'Tempel Tautan (G-Drive) atau Unggah File',
    'exec.placeholder.notes': 'Tuliskan temuan atau observasi auditor...',
    'exec.placeholder.action': 'Jelaskan rencana perbaikan dan target waktu...',
    'exec.status.compliant': 'Memenuhi (M)',
    'exec.status.observation': 'Observasi (OB)',
    'exec.status.noncompliant': 'Tidak Memenuhi (TM)',
    'exec.alert.upload_success': 'File berhasil diunggah!',
    'exec.alert.submit_auditee': 'Kirim Self-Assessment? Auditor akan mendapatkan notifikasi untuk melakukan verifikasi.',
    'exec.alert.submit_auditor': 'Selesaikan Verifikasi? Laporan akan dikirim ke Kepala Unit untuk validasi akhir.',
    'exec.alert.approve_dept': 'Validasi Hasil Audit? Audit akan ditandai sebagai Selesai (Completed).',
    
    // Status Abbreviations & Terms
    'abbr.compliant': 'M',
    'abbr.noncompliant': 'TM',
    'abbr.observation': 'OB',
    'term.compliant': 'Memenuhi (M)',
    'term.noncompliant': 'Tidak Memenuhi (TM)',
    'term.observation': 'Observasi (OB)',

    // Reports
    'report.title': 'Laporan Audit Mutu Internal',
    'report.aiTitle': 'Analisis Cerdas Gemini AI',
    'report.aiEmpty': 'Klik tombol di bawah untuk mendapatkan ringkasan eksekutif dan rekomendasi strategis otomatis berbasis AI.',
    'report.btn.analyze': 'Mulai Analisis AI',
    'report.btn.analyzing': 'Sedang Menganalisis...',
    'report.btn.export': 'Unduh PDF',
    'report.btn.reopen': 'Buka Kembali (Reopen)',
    'report.execSummary': 'Ringkasan Eksekutif',
    'report.recommendations': 'Rekomendasi Strategis',
    'report.details': 'Rincian Temuan',
    'report.compliance_summary': 'Ringkasan Kepatuhan',
    'report.chart.radar': 'Peta Ketercapaian Standar',
    'report.chart.subtitle': '% Kepatuhan per Kategori',
    'report.filter': 'FILTER STATUS:',
    'report.shown': 'Ditampilkan',
    'report.th.code': 'Kode',
    'report.th.question': 'Indikator / Pertanyaan',
    'report.th.status': 'Status',
    'report.th.notes': 'Bukti & Catatan',
    'report.reopenConfirm': 'Kembalikan status audit menjadi "Sedang Berjalan"? Auditor dan Auditee dapat mengubah isian kembali.',
    'report.emptyFilter': 'Tidak ada data yang sesuai dengan filter yang dipilih.',
    
    // Repository
    'repo.title': 'Repositori Laporan Audit',
    'repo.access.admin': 'Akses Admin: Menampilkan seluruh arsip audit.',
    'repo.access.user': 'Menampilkan arsip laporan untuk unit kerja Anda.',
    'repo.all': 'Semua Laporan',
    'repo.completed': 'Selesai',
    'repo.progress': 'Berjalan',
    'repo.search': 'Cari Laporan...',
    'repo.empty': 'Tidak ada laporan yang ditemukan.',
    'repo.btn.view': 'Lihat Detail',

    // Management
    'mgmt.user.title': 'Manajemen Pengguna',
    'mgmt.user.desc': 'Kelola akses akun dan peran pengguna dalam sistem.',
    'mgmt.btnAdd': 'Tambah Pengguna',
    'mgmt.th.name': 'Nama Lengkap',
    'mgmt.th.role': 'Peran',
    'mgmt.th.dept': 'Unit Kerja',
    'mgmt.th.status': 'Status Akun',
    'mgmt.th.action': 'Aksi',
    'mgmt.modal.add': 'Tambah Pengguna Baru',
    'mgmt.modal.edit': 'Edit Data Pengguna',
    'mgmt.form.name': 'Nama Lengkap',
    'mgmt.form.user': 'Username',
    'mgmt.form.pass': 'Password',
    'mgmt.form.pass.edit': 'Password (Kosongkan jika tidak diubah)',
    'mgmt.form.role': 'Peran Akses',
    'mgmt.form.dept': 'Departemen / Unit',
    'mgmt.btn.save': 'Simpan',
    'mgmt.btn.update': 'Perbarui',
    'mgmt.btn.cancel': 'Batal',
    'mgmt.del.title': 'Hapus Data?',
    'mgmt.del.msg': 'Anda akan menghapus data berikut secara permanen:',
    'mgmt.del.confirm': 'Hapus Permanen',
    
    'master.title': 'Data Unit Kerja',
    'master.desc': 'Kelola referensi Unit, Program Studi, Fakultas, dan Biro.',
    'master.btn.add': 'Tambah Unit',
    'master.th.code': 'Kode Unit',
    'master.th.name': 'Nama Unit',
    'master.th.type': 'Tipe',
    'master.th.faculty': 'Induk (Parent)',
    'master.modal.add': 'Tambah Unit Baru',
    'master.modal.edit': 'Edit Unit Kerja',
    'master.form.code': 'Kode Unit',
    'master.form.name': 'Nama Unit',
    'master.form.type': 'Tipe Unit',
    'master.form.faculty': 'Unit Induk',
    'master.form.head': 'Jabatan Pimpinan',

    'mgmt.tmpl.title': 'Instrumen Audit',
    'mgmt.tmpl.desc': 'Kelola standar referensi dan butir pertanyaan audit.',
    'mgmt.set.title': 'Pengaturan Sistem',
    'mgmt.set.desc': 'Konfigurasi identitas aplikasi dan siklus audit.',
    'mgmt.set.brand': 'Tampilan Aplikasi',
    'mgmt.set.appName': 'Nama Aplikasi',
    'mgmt.set.theme': 'Warna Tema',
    'mgmt.set.logo': 'Logo Aplikasi',
    'mgmt.set.cycle': 'Konfigurasi Siklus',
    'mgmt.set.period': 'Periode Audit Aktif',
    'mgmt.set.std': 'Standar Default',
    'mgmt.set.save': 'Simpan Perubahan',
  },
  en: {
    // Global & Common
    'app.name': 'SPM~ITSB',
    'status.pending': 'Pending Schedule',
    'status.planned': 'Scheduled',
    'status.progress': 'In Progress',
    'status.submitted': 'Auditor Verification',
    'status.review': 'Dept Head Review',
    'status.completed': 'Completed',
    'status.user_active': 'Active',
    'status.user_inactive': 'Inactive',
    'status.user_role': 'User Role',
    
    'role.superadmin': 'Super Admin',
    'role.admin': 'Administrator',
    'role.lead': 'Lead Auditor',
    'role.auditor': 'Auditor',
    'role.depthead': 'Dept Head',
    'role.auditee': 'Auditee',

    // Alerts & Errors
    'alert.file_too_big': 'File size is too big (Max 5MB).',
    'alert.no_evidence': 'No evidence/link to open.',
    'alert.file_error': 'Failed to open file. Data might be corrupted.',
    'alert.file_invalid': 'Invalid file data.',

    // Confirmations
    'confirm.general': 'Action Confirmation',
    'confirm.save': 'Are you sure you want to SAVE this data?',
    'confirm.delete': 'Are you sure you want to DELETE this data? This cannot be undone.',
    'confirm.update': 'Are you sure you want to UPDATE this data?',
    'confirm.add': 'Are you sure you want to ADD this new data?',
    'confirm.action': 'Are you sure you want to proceed?',
    'confirm.cancel': 'Are you sure you want to cancel?',
    'confirm.yes': 'Yes, Proceed',
    'confirm.no': 'Cancel',

    // Sidebar
    'nav.dashboard': 'Dashboard',
    'nav.schedule': 'Audit Schedule',
    'nav.userMgmt': 'User Management',
    'nav.template': 'Audit Instruments',
    'nav.master': 'Work Units',
    'nav.newAudit': 'New Assignment',
    'nav.execution': 'Audit Execution',
    'nav.report': 'Reports & AI',
    'nav.settings': 'System Settings',
    'nav.logout': 'Logout',
    'nav.my_assign': 'My Assignments',
    'nav.my_audits': 'My Unit Audits',
    'nav.my_reports': 'Report History',
    'nav.dept_reports': 'Unit Reports',
    'nav.all_exec': 'Execution Monitor',
    'nav.all_active': 'Active Audits',

    // Dashboard
    'dash.title': 'Audit Dashboard',
    'dash.subtitle': 'Overview of internal quality assurance activities.',
    'dash.btnNew': '+ New Assignment',
    'dash.total': 'Total Audits',
    'dash.inProgress': 'In Progress',
    'dash.completed': 'Completed',
    'dash.findings': 'Major Findings',
    'dash.submitted': 'Auditor Verification',
    'dash.review': 'Dept Head Review',
    'dash.recentHistory': 'Recent Audit Activities',
    'dash.th.dept': 'Unit / Dept',
    'dash.th.std': 'Standard',
    'dash.th.status': 'Status',
    'dash.th.date': 'Date',
    'dash.th.auditor': 'Auditor',
    'dash.empty': 'No audit data available. Please create a new assignment.',
    'dash.welcome.auditee': 'Work Unit Area: ',
    'dash.welcome.auditee.msg': 'This page displays audit data relevant to your unit. Please complete evidence and action plans for "In Progress" audits.',
    'dash.welcome.auditor': 'Auditor Workspace',
    'dash.welcome.auditor.msg': 'Displaying your audit assignments. Please assess compliance, verify evidence, and provide findings.',

    // Audit Schedule (Jadwal)
    'sched.title': 'Audit Schedule',
    'sched.subtitle': 'Plan, schedule, and visualize audit timelines.',
    'sched.view.list': 'List View',
    'sched.view.calendar': 'Calendar View',
    'sched.btn.new': '+ New Schedule',
    'sched.upcoming': 'Upcoming / Pending Schedule',
    'sched.history': 'Audit History (Active & Completed)',
    'sched.btn.start_all': 'Start All (Planned)',
    'sched.empty_upcoming': 'No upcoming audits scheduled.',
    'sched.empty_history': 'No audit history available.',
    'sched.modal.new_title': 'Schedule New Audit',
    'sched.modal.reschedule_title': 'Reschedule Audit',
    'sched.label.date': 'Scheduled Date',
    'sched.label.auditor': 'Assigned Auditor',
    'sched.label.unit': 'Unit / Auditee',
    'sched.label.std': 'Standard',
    'sched.label.name': 'Audit Name',
    'sched.confirm.title': 'Confirm Schedule',
    'sched.confirm.msg': 'This schedule will be sent to the Dept Head for approval.',
    'sched.action.start': 'Start',
    'sched.action.reschedule': 'Reschedule',
    'sched.action.delete': 'Delete',
    'sched.alert.overdue': 'Overdue',

    // New Audit
    'new.title': 'Assignment Config',
    'new.step1': 'Assignment Data',
    'new.step2': 'Review Instrument',
    'new.editor.title': 'Review Audit Instrument',
    'new.editor.subtitle': 'Review, edit, or manually add audit questions before sending.',
    'new.label.std': '1. Select Standard (Required)',
    'new.label.unit': '2. Select Auditee (Unit/Dept)',
    'new.label.auditor': '3. Assign Auditor (All Active Users)',
    'new.label.name': '4. Audit Assignment Name',
    'new.label.desc': '5. Description / Notes',
    'new.placeholder.unit': '-- Select Unit / Program --',
    'new.placeholder.auditor': '-- Select Auditor --',
    'new.warn.conflict': 'Info: Auditors from the same unit are hidden to avoid Conflict of Interest.',
    'new.btn.cancel': 'Cancel',
    'new.btn.next': 'Next',
    'new.btn.back': 'Back',
    'new.btn.finalize': 'Send Assignment',
    'new.btn.generate': 'Processing...',
    'new.btn.addManual': '+ Add Question',
    'new.error': 'Failed to connect to AI service. Please check your connection.',
    'new.access_denied': 'Access Denied',
    'new.access_msg': 'You do not have permission to create new Audit Assignments.',
    'new.confirm.title': 'Send Assignment?',
    'new.confirm.msg': 'This assignment will be sent to the Dept Head for schedule confirmation.',
    'new.confirm.wait': 'Status: Waiting for Confirmation',
    'new.confirm.wait_msg': 'The audit cannot start (In Progress) until the Dept Head approves the proposed schedule.',
    'new.del.title': 'Delete Question?',
    'new.del.msg': 'This question will be removed from the current audit instrument list.',
    'new.del.confirm': 'Yes, Delete',

    // Execution
    'exec.list.title': 'Audit Execution',
    'exec.list.subtitle': 'Select an audit to start filling working papers or verifying.',
    'exec.search': 'Search Unit / Audit Name...',
    'exec.no_active': 'No active audits',
    'exec.no_active_msg': 'All audit tasks are completed or not yet in execution phase.',
    'exec.progress': 'Progress',
    'exec.filter.all': 'All',
    'exec.filter.unfilled': 'Unfilled',
    'exec.search_placeholder': 'Search questions/indicators...',
    'exec.no_match': 'No questions match your filter.',
    'exec.btn.save': 'Save Draft',
    'exec.btn.complete': 'Complete / Submit',
    'exec.btn.submit_assess': 'Submit Assessment',
    'exec.btn.verify_send': 'Verify & Send',
    'exec.btn.approve': 'Approve',
    'exec.btn.back': 'Back',
    'exec.btn.open_file': 'Open Evidence',
    'exec.label.evidence': 'Evidence',
    'exec.label.notes': 'Auditor Notes',
    'exec.label.action_plan': 'Action Plan (RTL)',
    'exec.label.verification': 'Auditor Verification',
    'exec.label.verdict': 'Auditor Verdict',
    'exec.label.self_eval': 'Auditee Self Assessment',
    'exec.label.claim': 'Self Assessment Claim',
    'exec.help.upload': '*You can paste an external URL OR upload a file (Max 5MB).',
    'exec.placeholder.evidence': 'Paste Link (G-Drive) or Upload File',
    'exec.placeholder.notes': 'Write findings or observations...',
    'exec.placeholder.action': 'Explain improvement plan and target date...',
    'exec.status.compliant': 'Compliant (C)',
    'exec.status.observation': 'Observation (OB)',
    'exec.status.noncompliant': 'Non-Compliant (NC)',
    'exec.alert.upload_success': 'File uploaded successfully!',
    'exec.alert.submit_auditee': 'Send Self-Assessment? Auditor will be notified for verification.',
    'exec.alert.submit_auditor': 'Complete Verification? Report will be sent to Dept Head for final validation.',
    'exec.alert.approve_dept': 'Validate Audit Results? Audit will be marked as Completed.',

    // Status Abbreviations & Terms
    'abbr.compliant': 'C',
    'abbr.noncompliant': 'NC',
    'abbr.observation': 'OB',
    'term.compliant': 'Compliant',
    'term.noncompliant': 'Non-Compliant',
    'term.observation': 'Observation',

    // Reports
    'report.title': 'Internal Quality Audit Report',
    'report.aiTitle': 'Gemini AI Smart Analysis',
    'report.aiEmpty': 'Click below to get an automated executive summary and strategic recommendations using AI.',
    'report.btn.analyze': 'Start AI Analysis',
    'report.btn.analyzing': 'Analyzing...',
    'report.btn.export': 'Download PDF',
    'report.btn.reopen': 'Re-open Audit',
    'report.execSummary': 'Executive Summary',
    'report.recommendations': 'Strategic Recommendations',
    'report.details': 'Findings Details',
    'report.compliance_summary': 'Compliance Summary',
    'report.chart.radar': 'Standard Achievement Map',
    'report.chart.subtitle': '% Compliance per Category',
    'report.filter': 'FILTER STATUS:',
    'report.shown': 'Shown',
    'report.th.code': 'Code',
    'report.th.question': 'Indicator / Question',
    'report.th.status': 'Status',
    'report.th.notes': 'Evidence & Notes',
    'report.reopenConfirm': 'Revert audit status to "In Progress"? Auditor and Auditee can edit entries again.',
    'report.emptyFilter': 'No data matches the selected filter.',

    // Repository
    'repo.title': 'Audit Report Repository',
    'repo.access.admin': 'Admin Access: Viewing all audit archives.',
    'repo.access.user': 'Viewing audit archives authorized for your unit.',
    'repo.all': 'All Reports',
    'repo.completed': 'Completed',
    'repo.progress': 'In Progress',
    'repo.search': 'Search Report...',
    'repo.empty': 'No reports found.',
    'repo.btn.view': 'View Details',

    // Management
    'mgmt.user.title': 'User Management',
    'mgmt.user.desc': 'Manage user accounts and access roles.',
    'mgmt.btnAdd': 'Add User',
    'mgmt.th.name': 'Full Name',
    'mgmt.th.role': 'Role',
    'mgmt.th.dept': 'Work Unit',
    'mgmt.th.status': 'Account Status',
    'mgmt.th.action': 'Action',
    'mgmt.modal.add': 'Add New User',
    'mgmt.modal.edit': 'Edit User Details',
    'mgmt.form.name': 'Full Name',
    'mgmt.form.user': 'Username',
    'mgmt.form.pass': 'Password',
    'mgmt.form.pass.edit': 'Password (Leave blank if unchanged)',
    'mgmt.form.role': 'Access Role',
    'mgmt.form.dept': 'Department / Unit',
    'mgmt.btn.save': 'Save',
    'mgmt.btn.update': 'Update',
    'mgmt.btn.cancel': 'Cancel',
    'mgmt.del.title': 'Delete Data?',
    'mgmt.del.msg': 'You are about to permanently delete:',
    'mgmt.del.confirm': 'Delete Permanently',

    'master.title': 'Work Units Data',
    'master.desc': 'Manage Units, Study Programs, Faculties, and Bureaus references.',
    'master.btn.add': 'Add Unit',
    'master.th.code': 'Unit Code',
    'master.th.name': 'Unit Name',
    'master.th.type': 'Type',
    'master.th.faculty': 'Parent Unit',
    'master.modal.add': 'Add New Unit',
    'master.modal.edit': 'Edit Work Unit',
    'master.form.code': 'Unit Code',
    'master.form.name': 'Unit Name',
    'master.form.type': 'Unit Type',
    'master.form.faculty': 'Parent Unit',
    'master.form.head': 'Head Position',

    'mgmt.tmpl.title': 'Audit Instruments',
    'mgmt.tmpl.desc': 'Manage reference standards and audit questions.',
    'mgmt.set.title': 'System Settings',
    'mgmt.set.desc': 'Configure application identity and audit cycles.',
    'mgmt.set.brand': 'App Appearance',
    'mgmt.set.appName': 'Application Name',
    'mgmt.set.theme': 'Theme Color',
    'mgmt.set.logo': 'Application Logo',
    'mgmt.set.cycle': 'Cycle Configuration',
    'mgmt.set.period': 'Active Audit Period',
    'mgmt.set.std': 'Default Standard',
    'mgmt.set.save': 'Save Changes',
  }
};

export const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider: FC<{ children: ReactNode }> = ({ children }) => {
  const [language, setLanguage] = useState<Language>('id');

  const t = (key: string): string => {
    // @ts-ignore
    const text = translations[language][key];
    if (!text) {
        // Fallback or warning if translation is missing
        return key;
    }
    return text;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
